In [1]:
"""
代码参考自：机器之心
主要添加注释
"""

import tensorflow as tf  #导入tf
import numpy as np
hello = tf.constant('Hello, TensorFlow!')  # 定义tf常量
sess = tf.Session()       # 创建tf会话
print(sess.run(hello))    # 执行会话

b'Hello, TensorFlow!'


In [2]:
import numpy as np


a = tf.constant(2, tf.int16)   # 创建常量2 
b = tf.constant(4, tf.float32)
c = tf.constant(8, tf.float32)

d = tf.Variable(2, tf.int16)   # 创建变量2
e = tf.Variable(4, tf.float32)
f = tf.Variable(8, tf.float32)

g = tf.constant(np.zeros(shape=(2,2), dtype=np.float32)) #可以正常声明变量,[[0,0],[0,0]]

h = tf.zeros([11], tf.int16)  # [0,0,0....]
i = tf.ones([2,2], tf.float32) # [[1,1],[1,1]]
j = tf.zeros([1000,4,3], tf.float64) # 三维0矩阵

k = tf.Variable(tf.zeros([2,2], tf.float32)) # 变量矩阵
l = tf.Variable(tf.zeros([5,6,5], tf.float32)) # 变量矩阵

In [3]:
a = tf.constant(2, tf.int16)     # 常量2
b = tf.constant(4, tf.float32)   # 常量4

graph = tf.Graph()   # 创建一个图，可以通过tensorboard用图形化界面展示出来流程结构, 可以整合一段代码为一个整体存在于一个图中             
with graph.as_default(): # 返回一个上下文管理器，这个上下文管理器使用这个图作为默认的图
    a = tf.Variable(8, tf.float32) # 创建变量8
    b = tf.Variable(tf.zeros([2,2], tf.float32)) # 创建[[0,0],[0,0]]
    
with tf.Session(graph=graph) as session: # 开启会话
    tf.global_variables_initializer().run() # 初始化参数
    print(f)   # 打印f
    print(session.run(a)) 
    print(session.run(b))

<tf.Variable 'Variable_2:0' shape=() dtype=int32_ref>
8
[[0. 0.]
 [0. 0.]]


In [4]:
a=tf.constant([1,2],name="a")
b=tf.constant([2,4],name="b")
result = a+b
print(result) # 

Tensor("add:0", shape=(2,), dtype=int32)


In [5]:
a=tf.constant([1,2,3,4])
b=tf.constant([1,2,3,4])
result=a+b
sess=tf.Session()  # 创建会话一
print(sess.run(result))
sess.close

#输出 [2 4 6 8]

with tf.Session() as sess: # 创建会话二
    a=tf.constant([1,2,3,4])
    b=tf.constant([1,2,3,4])
    result=a+b
    print(sess.run(result))
    
#输出 [2 4 6 8]

[2 4 6 8]
[2 4 6 8]


In [6]:

w1=tf.Variable(tf.random_normal([1,2],stddev=1,seed=1))  # 创建变量，正态分布

#因为需要重复输入x，而每建一个x就会生成一个结点，计算图的效率会低。所以使用占位符
x=tf.placeholder(tf.float32,shape=(1,2)) # 占位符
x1=tf.constant([[0.7,0.9]])       # 常量矩阵

a=x+w1                
b=x1+w1

sess=tf.Session()
sess.run(tf.global_variables_initializer())
#运行y时将占位符填上，feed_dict为字典，变量名不可变
y_1=sess.run(a,feed_dict={x:[[0.7,0.9]]})  # feed_dict字典，传入需要的数据
y_2=sess.run(b)  
print(y_1)
print(y_2)
sess.close

[[-0.11131823  2.3845987 ]]
[[-0.11131823  2.3845987 ]]


<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x7ff18d9d19e8>>

In [7]:
list_of_points1_ = [[1,2], [3,4], [5,6], [7,8]]
list_of_points2_ = [[15,16], [13,14], [11,12], [9,10]]
list_of_points1 = np.array([np.array(elem).reshape(1,2) for elem in list_of_points1_])
list_of_points2 = np.array([np.array(elem).reshape(1,2) for elem in list_of_points2_])

graph = tf.Graph() # 创建图
with graph.as_default():
    
    #我们使用 tf.placeholder() 创建占位符 ，在 session.run() 过程中再投递数据 
    point1 = tf.placeholder(tf.float32, shape=(1, 2))
    point2 = tf.placeholder(tf.float32, shape=(1, 2))
    
    def calculate_eucledian_distance(point1, point2):
        difference = tf.subtract(point1, point2) # 减法
        power2 = tf.pow(difference, tf.constant(2.0, shape=(1,2))) # 指数
        add = tf.reduce_sum(power2) # 求和，把每个位置的值加起来
        eucledian_distance = tf.sqrt(add)  # 求根号[(x1-y1）^2+(x2-y2)^2]^(1/2)
        return eucledian_distance
    
    dist = calculate_eucledian_distance(point1, point2)
    
with tf.Session(graph=graph) as session: # 创建会话
    tf.global_variables_initializer().run() # 初始化
    for ii in range(len(list_of_points1)):  # 遍历列表，按行
        point1_ = list_of_points1[ii] #行1
        point2_ = list_of_points2[ii] #行2
        
        #使用feed_dict将数据投入到[dist]中
        feed_dict = {point1 : point1_, point2 : point2_} # 组成字典
        distance = session.run([dist], feed_dict=feed_dict) # 计算欧式距离
        print("the distance between {} and {} -> {}".format(point1_, point2_, distance)) # 打印结果

the distance between [[1 2]] and [[15 16]] -> [19.79899]
the distance between [[3 4]] and [[13 14]] -> [14.142136]
the distance between [[5 6]] and [[11 12]] -> [8.485281]
the distance between [[7 8]] and [[ 9 10]] -> [2.828427]


In [8]:
import tensorflow as tf
from numpy.random import RandomState

batch_size=10
w1=tf.Variable(tf.random_normal([2,3],stddev=1,seed=1)) # 创建随机数矩阵2*3
w2=tf.Variable(tf.random_normal([3,1],stddev=1,seed=1)) # 创建随机数矩阵3*1


# None 可以根据batch 大小确定维度，在shape的一个维度上使用None，方便不大的batch
x=tf.placeholder(tf.float32,shape=(None,2))  # 创建占位符
y=tf.placeholder(tf.float32,shape=(None,1))  # 创建占位符

a=tf.nn.relu(tf.matmul(x,w1))     # x*w1
yhat=tf.nn.relu(tf.matmul(a,w2))  # a*w2

#定义交叉熵为损失函数，训练过程使用Adam算法最小化交叉熵
cross_entropy=-tf.reduce_mean(y*tf.log(tf.clip_by_value(yhat,1e-10,1.0)))  
#tf.reduce_mean计算所有元素的均值，如指定axis则沿指定轴取均值。tf.clip_by_value基于定义的min与max对tesor数据进行截断操作，目的是为了应对梯度爆发或者梯度消失的情况

train_step=tf.train.AdamOptimizer(0.001).minimize(cross_entropy)   # Adam优化算法：是一个寻找全局最优点的优化算法，引入了二次方梯度校正。

rdm=RandomState(1)   # 随机数生成器
data_size=512

#生成两个特征，共data_size个样本
X=rdm.rand(data_size,2)  # 生成随机样本
#定义规则给出样本标签，所有x1+x2<1的样本认为是正样本，其他为负样本。Y，1为正样本
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]

with tf.Session() as sess: # 创建会话
    sess.run(tf.global_variables_initializer())  # 初始化
    print(sess.run(w1))
    print(sess.run(w2))
    steps=15001
    for i in range(steps): # 循环
        
        #选定每一个批量读取的首尾位置，确保在1个epoch内采样训练
        start = i * batch_size % data_size
        end = min(start + batch_size,data_size)
        sess.run(train_step,feed_dict={x:X[start:end],y:Y[start:end]}) #启动优化器训练，传入数据
        if i % 1000 == 0:
            training_loss= sess.run(cross_entropy,feed_dict={x:X,y:Y}) #每1000轮，使用交叉熵函数进行计算输出，评估训练效果
            print("在迭代 %d 次后，训练损失为 %g"%(i,training_loss))
        if i == steps-1: # 最后一轮
            print(sess.run(w1))
            print(sess.run(w2))#输出更新后的权重矩阵

[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
在迭代 0 次后，训练损失为 0.308504
在迭代 1000 次后，训练损失为 0.0393406
在迭代 2000 次后，训练损失为 0.0182158
在迭代 3000 次后，训练损失为 0.0104779
在迭代 4000 次后，训练损失为 0.00680374
在迭代 5000 次后，训练损失为 0.00446512
在迭代 6000 次后，训练损失为 0.00296797
在迭代 7000 次后，训练损失为 0.00218553
在迭代 8000 次后，训练损失为 0.00179452
在迭代 9000 次后，训练损失为 0.0013211
在迭代 10000 次后，训练损失为 0.000957699
在迭代 11000 次后，训练损失为 0.00081103
在迭代 12000 次后，训练损失为 0.000643147
在迭代 13000 次后，训练损失为 0.00047439
在迭代 14000 次后，训练损失为 0.00030086
在迭代 15000 次后，训练损失为 0.000137936
[[-0.8113182  3.8425548  3.3816528]
 [-2.4427042  1.9863598  3.5072231]]
[[-0.8113182]
 [ 4.029077 ]
 [ 2.602852 ]]


上面的代码定义了一个简单的三层全连接网络（输入层、隐藏层和输出层分别为2、3和2个神经元），隐藏层和输出层的激活函数使用的是ReLU函数。该模型训练的样本总数为512，每次迭代读取的批量为10。这个简单的全连接网络以交叉熵为损失函数，并使用Adam优化算法进行权重更新。

其中需要注意的几个函数如tf.nn.relu()代表调用ReLU激活函数，tf.matmul()为矩阵乘法等。tf.clip_by_value(yhat,1e-10,1.0)这一语句代表的是截断yhat的值，因为这一语句是嵌套在tf.log()函数内的，所以我们需要确保yhat的取值不会导致对数无穷大。

tf.train.AdamOptimizer(learning_rate).minimize(cost_function)是进行训练的函数，其中我们采用的是Adam优化算法更新权重，并且需要提供学习速率和损失函数这两个参数。后面就是生成训练数据，X=rdm.rand(512,2)表示随机生成512个样本，每个样本有两个特征值。最后就是迭代运行了，这里我们计算出每一次迭代抽取数据的起始位置（start）和结束位置（end），并且每一次抽取的数据量为前面我们定义的批量，如果一个epoch最后剩余的数据少于批量大小，那就只是用剩余的数据进行训练。最后两句代码是为了计算训练损失并迭代一些次数后输出训练损失。

In [6]:
import numpy as np
import pickle # 用于python特有的类型和python的数据类型间进行转换
import json
import os

#定义一些预处理函数

def flatten_tf_array(array):
    shape = array.get_shape().as_list() # get_shape()用于获取tensor的大小，返回一个元组，通过as_list()方法转成list
    return tf.reshape(array, [shape[0], shape[1] * shape[2] * shape[3]]) # 变换形状

def accuracy(predictions, labels): # 计算准确率
    return (100.0 * np.sum(np.argmax(predictions, 1) == np.argmax(labels, 1)) / predictions.shape[0]) # 比较predictions和label，求准确率
# np.argmax(a)取出a中元素最大值所对应的索引，np.argmax(a，1)对a按行取最大值索引

def randomize(dataset, labels):
    permutation = np.random.permutation(labels.shape[0]) 
    #函数shuffle与permutation都是对原来的数组进行重新洗牌（即随机打乱原来的元素顺序）；区别在于shuffle直接在原来的数组上进行操作，
    #改变原来数组的顺序，无返回值。而permutation不直接在原来的数组上进行操作，而是返回一个新的打乱顺序的数组，并不改变原来的数组。
    shuffled_dataset = dataset[permutation, :, :] # 取乱序后的训练集
    shuffled_labels = labels[permutation]  # 取乱序后的label
    return shuffled_dataset, shuffled_labels  # 返回乱序后的训练集，label

def one_hot_encode(np_array):  # one-hot编码, 两个array做==操作，相当于两array逐个元素比较是否相等，相等为1，否则为0.最后形成一个n*10的矩阵，n为np_array的大小
    return (np.arange(10) == np_array[:,None]).astype(np.float32) # np.arange(10)返回1-9的数组，astype类型转换

def reformat_data(dataset, labels, image_width, image_height, image_depth):
    # 遍历图片集，转成w*h*d, 再整成数组
    np_dataset_ = np.array([np.array(image_data).reshape(image_width, image_height, image_depth) for image_data in dataset])
    # 对label进行one-hot编码
    np_labels_ = one_hot_encode(np.array(labels, dtype=np.float32))
    np_dataset, np_labels = randomize(np_dataset_, np_labels_) # 乱序
    return np_dataset, np_labels # 返回训练集，label

In [7]:
cifar10_folder = './cifar-10-batches-py/' # 数据路径
train_datasets = ['data_batch_1', 'data_batch_2', 'data_batch_3', 'data_batch_4', 'data_batch_5', ] # 训练集
test_dataset = ['test_batch'] # 测试集
c10_image_height = 32 # 图片高度
c10_image_width = 32  # 图片宽度
c10_image_depth = 3   # 图片深度
c10_num_labels = 10   # label种类数
c10_image_size = 32 #Ahmet Taspinar的代码缺少了这一语句。图片大小？

with open(cifar10_folder + test_dataset[0], 'rb') as f0: # 载入数据,以二进制形式打开文件
    c10_test_dict = pickle.load(f0, encoding='bytes')    # 反序列化对象，将文件中的数据解析为一个python对象

c10_test_dataset, c10_test_labels = c10_test_dict[b'data'], c10_test_dict[b'labels'] # 分割测试集的feature，label
#改变图片形状、对label进行one-hot编码，乱序
test_dataset_cifar10, test_labels_cifar10 = reformat_data(c10_test_dataset, c10_test_labels, c10_image_size, c10_image_size, c10_image_depth)

c10_train_dataset, c10_train_labels = [], [] # 存训练集的容器
for train_dataset in train_datasets:  # 遍历训练集，训练集分成了5份，所以需要遍历，合并到一起
    with open(cifar10_folder + train_dataset, 'rb') as f0: # 以二进制形式打开文件
        c10_train_dict = pickle.load(f0, encoding='bytes') # 反序列化对象
        c10_train_dataset_, c10_train_labels_ = c10_train_dict[b'data'], c10_train_dict[b'labels'] # 分割测试集的feature，label
 
        c10_train_dataset.append(c10_train_dataset_) #合并特征
        c10_train_labels += c10_train_labels_  #合并label

c10_train_dataset = np.concatenate(c10_train_dataset, axis=0) # 数组拼接，沿纵轴，将多个list进行拼接
#改变图片形状、对label进行one-hot编码，乱序
train_dataset_cifar10, train_labels_cifar10 = reformat_data(c10_train_dataset, c10_train_labels, c10_image_size, c10_image_size, c10_image_depth)
del c10_train_dataset # 删除原始特征
del c10_train_labels # 删除原始label

print("训练集包含以下标签: {}".format(np.unique(c10_train_dict[b'labels'])))    # np.unique()该函数是去除数组中的重复数字，并进行排序之后输出
print('训练集维度', train_dataset_cifar10.shape, train_labels_cifar10.shape)
print('测试集维度', test_dataset_cifar10.shape, test_labels_cifar10.shape)


训练集包含以下标签: [0 1 2 3 4 5 6 7 8 9]
训练集维度 (50000, 32, 32, 3) (50000, 10)
测试集维度 (10000, 32, 32, 3) (10000, 10)


In [11]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("./MNIST_DATA/", one_hot=True) #载入mnist数据,会自动下载数据
#input_data.read_data_sets("/tmp/MNIST_data/", False, one_hot=True) # 手动载入数据

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ./MNIST_DATA/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ./MNIST_DATA/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting ./MNIST_DATA/t10k-images-idx3-ubyte.gz
Extracting ./MNIST_DATA/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [12]:
print("Training data size: ", mnist.train.num_examples) 
print ("Validating data size: ", mnist.validation.num_examples) 
print ("Testing data size: ", mnist.test.num_examples) 

Training data size:  55000
Validating data size:  5000
Testing data size:  10000


In [13]:
print(mnist.train.images[0]) 
print(mnist.train.labels[0]) 
print(mnist.test.labels[0]) 
print(mnist.validation.labels[0]) 

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("./MNIST_DATA/", one_hot=True) # 载入数据，会自动下载


INPUT_NODE = 784  ## 输入层节点数。对于MNIST数据集，这个就等于图片的像素。  
OUTPUT_NODE = 10   # 输出层节点数。这个等于类别的数目。MNIST数据集中区分0-9十个数字，所以节点数是10
LAYER1_NODE = 500   ## 隐藏层节点数。这里使用只有一个隐藏层的网络结构作为样例，这个隐藏层500个节点   
                              
BATCH_SIZE = 100     #一个训练batch中的训练数据个数。数字越小，训练过程越接近随机梯度下降。数字越大，越接近梯度下降。   

# 模型相关的参数
LEARNING_RATE_BASE = 0.8      # 基础的学习率 
LEARNING_RATE_DECAY = 0.99    # 学习率的衰减率
REGULARAZTION_RATE = 0.0001   # 描述模型复杂度的正则化项在损失函数中的系数。
TRAINING_STEPS = 10000        # 训练轮数 
MOVING_AVERAGE_DECAY = 0.99   # 滑动平均衰减率

# 辅助函数。给定神经网络的输入和所有参数，计算神经网络的前向传播结果。
# 定义了一个使用ReLU激活函数的三层全连接神经网络。通过加入隐藏层实现了多层网络结构，通过ReLU激活函数实现了去线性化。
# 这个函数中也支持传入用于计算参数平均值的类，方便在测试时使用滑动平均模型。
def inference(input_tensor, avg_class, weights1, biases1, weights2, biases2):
    # 当没有提供滑动平均类时，直接使用参数当前的取值
    if avg_class == None:
        layer1 = tf.nn.relu(tf.matmul(input_tensor, weights1) + biases1) # relu(x*w+b)计算隐藏层的前向传播结果，使用了ReLU激活函数。
        # 计算输出层的前向传播结果。因为在计算损失函数时会一起计算softmax函数，所以这里不需要加入激活函数。
        # 而且不加入softmax不会影响预测结果。因为预测时使用的是不同类别对应节点输出值的相对大小，
        # 有没有softmax层对最后分类结果的计算并没有影响。所以在计算整个神经网络的前向传播时可以不加入最后的softmax层
        return tf.matmul(layer1, weights2) + biases2 # [relu(x*w+b)]*w2+b2

    else:
        # 使用滑动平均类
        # 首先使用avg_class.average函数计算得出变量的滑动平均值。
        # 然后计算相应的神经网络前向传播结果。
        layer1 = tf.nn.relu(tf.matmul(input_tensor, avg_class.average(weights1)) + avg_class.average(biases1))
        return tf.matmul(layer1, avg_class.average(weights2)) + avg_class.average(biases2)  
    
def train(mnist): # 训练
    x = tf.placeholder(tf.float32, [None, INPUT_NODE], name='x-input') # 占位符
    y_ = tf.placeholder(tf.float32, [None, OUTPUT_NODE], name='y-input')  # 占位符
    # 生成隐藏层的参数。
    weights1 = tf.Variable(tf.truncated_normal([INPUT_NODE, LAYER1_NODE], stddev=0.1)) # 变量，权重矩阵1
    # 截断的正态分布中输出随机值。 shape表示生成张量的维度，mean是均值，stddev是标准差。这个函数产生正太分布，均值和标准差自己设定。
    biases1 = tf.Variable(tf.constant(0.1, shape=[LAYER1_NODE])) # 变量，偏置1
    # 生成输出层的参数。
    weights2 = tf.Variable(tf.truncated_normal([LAYER1_NODE, OUTPUT_NODE], stddev=0.1))  # 变量，权重矩阵2
    biases2 = tf.Variable(tf.constant(0.1, shape=[OUTPUT_NODE]))  # 变量，偏置2

    # 计算不含滑动平均类的前向传播结果
    y = inference(x, None, weights1, biases1, weights2, biases2) 
    
    # 定义训练轮数及相关的滑动平均类 
    global_step = tf.Variable(0, trainable=False)
    variable_averages = tf.train.ExponentialMovingAverage(MOVING_AVERAGE_DECAY, global_step) # 就是采用滑动平均的方法更新参数
    variables_averages_op = variable_averages.apply(tf.trainable_variables()) 
    # tf.trainable_variables 返回所有 当前计算图中 在获取变量时未标记 trainable=False 的变量集合
    average_y = inference(x, variable_averages, weights1, biases1, weights2, biases2) # 含滑动平均的前向传播结果
    
    # 计算交叉熵及其平均值
    cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=y, labels=tf.argmax(y_, 1))
    #logits为神经网络输出层的输出，https://blog.csdn.net/ZJRN1027/article/details/80199248
    cross_entropy_mean = tf.reduce_mean(cross_entropy) # 用于计算张量tensor沿着指定的数轴（tensor的某一维度）上的的平均值，主要用作降维或者计算tensor（图像）的平均值。
    
    # 损失函数的计算
    regularizer = tf.contrib.layers.l2_regularizer(REGULARAZTION_RATE) # 可以计算给定参数的L2正则化项
    regularaztion = regularizer(weights1) + regularizer(weights2)   # 计算w1和w2的l2正则
    loss = cross_entropy_mean + regularaztion  # 交叉熵均值+l2正则
    
    # 设置指数衰减的学习率。
    learning_rate = tf.train.exponential_decay(  
        LEARNING_RATE_BASE,
        global_step,
        mnist.train.num_examples / BATCH_SIZE,
        LEARNING_RATE_DECAY,
        staircase=True) # 指数衰减法
    
    # 优化损失函数
    train_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss, global_step=global_step) 
    # GradientDescentOptimizer优化类，minimize,操作节点，用于最小化loss，global_step非none就会对其进行自增
    
    # 反向传播更新参数和更新每一个参数的滑动平均值
    with tf.control_dependencies([train_step, variables_averages_op]): 
        # 返回一个控制依赖的上下文管理器，使用with关键字可以让在这个上下文环境中的操作都在control_inputs 执行
        train_op = tf.no_op(name='train') # tf.no_op()什么都不做，仅做为点位符使用控制边界。

    # 计算正确率
    correct_prediction = tf.equal(tf.argmax(average_y, 1), tf.argmax(y_, 1)) 
    # tf.argmax()将每一行最大元素所在的索引记录下来，最后返回每一行最大元素所在的索引数组
    # tf.equal()该换数是比较两个矩阵相同的下标的元素，若相等则返回Ture，若不相等则返回False。
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32)) #求均值
    
    # 初始化回话并开始训练过程。
    with tf.Session() as sess:
        tf.global_variables_initializer().run() # 初始化变量
        validate_feed = {x: mnist.validation.images, y_: mnist.validation.labels} # 特征，label，组成的验证集字典
        test_feed = {x: mnist.test.images, y_: mnist.test.labels} # 测试集字典
        
        # 循环的训练神经网络。
        for i in range(TRAINING_STEPS):  # 循环训练
            if i % 1000 == 0:  # 每1000步，采用验证集进行评估模型效果
                validate_acc = sess.run(accuracy, feed_dict=validate_feed)
                print("After %d training step(s), validation accuracy using average model is %g " % (i, validate_acc))
            
            xs,ys=mnist.train.next_batch(BATCH_SIZE)  # 取batch
            sess.run(train_op,feed_dict={x:xs,y_:ys}) # 训练

        test_acc=sess.run(accuracy,feed_dict=test_feed)  # 训练完成后，在测试集上进行测试
        print(("After %d training step(s), test accuracy using average model is %g" %(TRAINING_STEPS, test_acc)))


Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ./MNIST_DATA/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ./MNIST_DATA/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting ./MNIST_DATA/t10k-images-idx3-ubyte.gz
Extracting ./MNIST_DATA/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [2]:
train(mnist)  训练

After 0 training step(s), validation accuracy using average model is 0.0784 
After 1000 training step(s), validation accuracy using average model is 0.9772 
After 2000 training step(s), validation accuracy using average model is 0.982 
After 3000 training step(s), validation accuracy using average model is 0.9838 
After 4000 training step(s), validation accuracy using average model is 0.9846 
After 5000 training step(s), validation accuracy using average model is 0.9838 
After 6000 training step(s), validation accuracy using average model is 0.9852 
After 7000 training step(s), validation accuracy using average model is 0.9844 
After 8000 training step(s), validation accuracy using average model is 0.9852 
After 9000 training step(s), validation accuracy using average model is 0.986 
After 10000 training step(s), test accuracy using average model is 0.9836


In [3]:
avg_class = None
train(mnist) # 将滑动平均类设为none,进行训练

After 0 training step(s), validation accuracy using average model is 0.1738 
After 1000 training step(s), validation accuracy using average model is 0.9766 
After 2000 training step(s), validation accuracy using average model is 0.9834 
After 3000 training step(s), validation accuracy using average model is 0.9826 
After 4000 training step(s), validation accuracy using average model is 0.9832 
After 5000 training step(s), validation accuracy using average model is 0.9838 
After 6000 training step(s), validation accuracy using average model is 0.9844 
After 7000 training step(s), validation accuracy using average model is 0.9852 
After 8000 training step(s), validation accuracy using average model is 0.9858 
After 9000 training step(s), validation accuracy using average model is 0.9856 
After 10000 training step(s), test accuracy using average model is 0.9823


In [8]:
LENET5_LIKE_BATCH_SIZE = 32  # lenet-5 batch大小
LENET5_LIKE_FILTER_SIZE = 5  # lenet-5 filter大小
LENET5_LIKE_FILTER_DEPTH = 16  # lenet-5 filter 深度
LENET5_LIKE_NUM_HIDDEN = 120   # 

def variables_lenet5_like(filter_size = LENET5_LIKE_FILTER_SIZE, 
                          filter_depth = LENET5_LIKE_FILTER_DEPTH, 
                          num_hidden = LENET5_LIKE_NUM_HIDDEN,
                          image_width = 32, image_height = 32, image_depth = 3, num_labels = 10):
    
    w1 = tf.Variable(tf.truncated_normal([filter_size, filter_size, image_depth, filter_depth], stddev=0.1)) # 采用高斯分布创建w1矩阵
    b1 = tf.Variable(tf.zeros([filter_depth])) # b1偏置

    w2 = tf.Variable(tf.truncated_normal([filter_size, filter_size, filter_depth, filter_depth], stddev=0.1)) # w2
    b2 = tf.Variable(tf.constant(1.0, shape=[filter_depth])) # b2
   
    w3 = tf.Variable(tf.truncated_normal([(image_width // 4)*(image_height // 4)*filter_depth , num_hidden], stddev=0.1)) # w3
    b3 = tf.Variable(tf.constant(1.0, shape = [num_hidden])) # b3

    w4 = tf.Variable(tf.truncated_normal([num_hidden, num_hidden], stddev=0.1)) # w4
    b4 = tf.Variable(tf.constant(1.0, shape = [num_hidden])) # b4
    
    w5 = tf.Variable(tf.truncated_normal([num_hidden, num_labels], stddev=0.1)) # w5
    b5 = tf.Variable(tf.constant(1.0, shape = [num_labels])) # b5
    variables = {
        'w1': w1, 'w2': w2, 'w3': w3, 'w4': w4, 'w5': w5,
        'b1': b1, 'b2': b2, 'b3': b3, 'b4': b4, 'b5': b5
    } # 组成字典
    return variables # 返回变量集

def model_lenet5_like(data, variables): # 定义lenet-5模型
    layer1_conv = tf.nn.conv2d(data, variables['w1'], [1, 1, 1, 1], padding='SAME') #卷积核1，张量输入、卷积核参数、步长参数、"SAME"是考虑边界，不足的时候用0去填充周围

    layer1_actv = tf.nn.relu(layer1_conv + variables['b1'])  # 卷积结果+偏置b1, 再使用relu激活函数
    layer1_pool = tf.nn.avg_pool(layer1_actv, [1, 2, 2, 1], [1, 2, 2, 1], padding='SAME') 
    # 平均池化，需要做池化的输入图像、池化窗口的大小、不同维度上的步长（第三个参数strides：不同维度上的步长，是一个长度为4的一维向量，[ 1, strides, strides, 1]，第一维和最后一维的数字要求必须是1。因为卷积层的步长只对矩阵的长和宽有效。）

    layer2_conv = tf.nn.conv2d(layer1_pool, variables['w2'], [1, 1, 1, 1], padding='SAME') # 卷积核2
    layer2_actv = tf.nn.relu(layer2_conv + variables['b2']) # 卷积结果2+偏置b2，relu激活函数
    layer2_pool = tf.nn.avg_pool(layer2_actv, [1, 2, 2, 1], [1, 2, 2, 1], padding='SAME') # 平均池化2
    
    flat_layer = flatten_tf_array(layer2_pool)  # 展成2维向量，k*l,k为样本数
    layer3_fccd = tf.matmul(flat_layer, variables['w3']) + variables['b3'] # 全连接层，对展平的结果*w+b
    layer3_actv = tf.nn.relu(layer3_fccd) # 使用relu激活
    layer3_drop = tf.nn.dropout(layer3_actv, 0.5)  # tf.nn.dropout是TensorFlow里面为了防止或减轻过拟合而使用的函数，它一般用在全连接层.在不同的训练过程中随机扔掉一部分神经元
    
    layer4_fccd = tf.matmul(layer3_actv, variables['w4']) + variables['b4']  # 全连接层，*w4+b4
    layer4_actv = tf.nn.relu(layer4_fccd) # relu激活
    layer4_drop = tf.nn.dropout(layer4_actv, 0.5) # dropout
    
    logits = tf.matmul(layer4_actv, variables['w5']) + variables['b5'] # 全连接层，*w5+b5
    return logits # 返回结果


#Variables used in the constructing and running the graph
num_steps = 10001 # 训练轮数
display_step = 1000 # 展示步长
learning_rate = 0.001 # 学习率
batch_size = 16  # batch大小

#定义数据的基本信息，传入变量
image_width = 32  # 图片宽度
image_height = 32  # 图片高度
image_depth = 3    # 图片深度
num_labels = 10    # label种数


test_dataset = test_dataset_cifar10   # 测试特征
test_labels = test_labels_cifar10     # 测试label
train_dataset = train_dataset_cifar10  # 训练特征
train_labels = train_labels_cifar10   # 训练label




graph = tf.Graph()  # 创建图
with graph.as_default():
    #1 首先使用占位符定义数据变量的维度
    tf_train_dataset = tf.placeholder(tf.float32, shape=(batch_size, image_width, image_height, image_depth)) # 占位符，用于训练特征
    tf_train_labels = tf.placeholder(tf.float32, shape = (batch_size, num_labels))  # 占位符，用于训练label
    tf_test_dataset = tf.constant(test_dataset, tf.float32)   # 测试集

    #2 然后初始化权重矩阵和偏置向量
    variables = variables_lenet5_like(image_width = image_width, image_height=image_height, image_depth = image_depth, num_labels = num_labels)


    #3 使用模型计算分类
    logits = model_lenet5_like(tf_train_dataset, variables)

    #4 使用带softmax的交叉熵函数计算预测标签和真实标签之间的损失函数
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=tf_train_labels))

    #5  采用Adam优化算法优化上一步定义的损失函数，给定学习率
    optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)

    # 执行预测推断
    train_prediction = tf.nn.softmax(logits)
    test_prediction = tf.nn.softmax(model_lenet5_like(tf_test_dataset, variables))


with tf.Session(graph=graph) as session:
    #初始化全部变量
    tf.global_variables_initializer().run()
    print('Initialized with learning_rate', learning_rate)
    for step in range(num_steps):  # 循环训练
        offset = (step * batch_size) % (train_labels.shape[0] - batch_size) # 计算偏移量
        batch_data = train_dataset[offset:(offset + batch_size), :, :, :] # 训练集
        batch_labels = train_labels[offset:(offset + batch_size), :] # 训练集label
        #在每一次批量中，获取当前的训练数据，并传入feed_dict以馈送到占位符中
        feed_dict = {tf_train_dataset : batch_data, tf_train_labels : batch_labels} # 将训练特征和label组成字典，用于后面训练
        _, l, predictions = session.run([optimizer, loss, train_prediction], feed_dict=feed_dict)#训练
        train_accuracy = accuracy(predictions, batch_labels)#计算准确率
        
        if step % display_step == 0: # 每1000步在测试集上评估模型准确率，并打印
            test_accuracy = accuracy(test_prediction.eval(), test_labels)
            message = "step {:04d} : loss is {:06.2f}, accuracy on training set {:02.2f} %, accuracy on test set {:02.2f} %".format(step, l, train_accuracy, test_accuracy)
            print(message)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Initialized with learning_rate 0.001
step 0000 : loss is 143.88, accuracy on training set 6.25 %, accuracy on test set 9.08 %
step 1000 : loss is 001.56, accuracy on training set 37.50 %, accuracy on test set 35.20 %
step 2000 : loss is 001.92, accuracy on training set 31.25 %, accuracy on test set 38.52 %
step 3000 : loss is 001.47, accuracy on training set 50.00 %, accuracy on test set 41.46 %
step 4000 : loss is 001.85, accuracy on training set 43.75 %, accuracy on test set 44.01 %
step 5000 : loss is 001.67, accuracy on training set 37.50 %, accuracy on test set 43.09 %
step 6000 : loss is 001.12, accuracy on training set 68.75 %, accuracy on test set 45.46 %
step 7000 : loss is 002.23, accuracy on training set 37.50 %, accuracy on test set 45.86 %
step 8000 : loss is 001.73, accuracy on traini